<a href="https://colab.research.google.com/github/wagh123/internship_projects/blob/main/Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Movie Recommendation System**

### **Import Library**

In [ ]:
import pandas as pd

import numpy as np

## **Import Dataset**

In [ ]:
df = pd.read_csv('Movies Recommendation.csv')

In [ ]:
df.head()

,Movie_ID,Movie_Title,Movie_Genre,Movie_Language,Movie_Budget,Movie_Popularity,Movie_Release_Date,Movie_Revenue,Movie_Runtime,Movie_Vote,...,Movie_Homepage,Movie_Keywords,Movie_Overview,Movie_Production_House,Movie_Production_Country,Movie_Spoken_Language,Movie_Tagline,Movie_Cast,Movie_Crew,Movie_Director
0,1,Four Rooms,Crime Comedy,en,4000000,22.876230,09-12-1995,4300000,98,6.5,...,NaN,hotel new year's eve witch bet hotel room,It's Ted the Bellhop's first night on the job....,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Twelve outrageous guests. Four scandalous requ...,Tim Roth Antonio Banderas Jennifer Beals Madon...,"[{'name': 'Allison Anders', 'gender': 1, 'depa...",Allison Anders
1,2,Star Wars,Adventure Action Science Fiction,en,11000000,126.393695,25-05-1977,775398007,121,8.1,...,http://www.starwars.com/films/star-wars-episod...,android galaxy hermit death star lightsaber,Princess Leia is captured and held hostage by ...,"[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twe...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","A long time ago in a galaxy far, far away...",Mark Hamill Harrison Ford Carrie Fisher Peter ...,"[{'name': 'George Lucas', 'gender': 2, 'depart...",George Lucas
2,3,Finding Nemo,Animation Family,en,94000000,85.688789,30-05-2003,940335536,100,7.6,...,http://movies.disney.com/finding-nemo,father son relationship harbor underwater fish...,"Nemo, an adventurous young clownfish, is unexp...","[{""name"": ""Pixar Animation Studios"", ""id"": 3}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","There are 3.7 trillion fish in the ocean, they...",Albert Brooks Ellen DeGeneres Alexander Gould ...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
3,4,Forrest Gump,Comedy Drama Romance,en,55000000,138.133331,06-07-1994,677945399,142,8.2,...,NaN,vietnam veteran hippie mentally disabled runni...,A man with a low IQ has accomplished great thi...,"[{""name"": ""Paramount Pictures"", ""id"": 4}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","The world will never be the same, once you've ...",Tom Hanks Robin Wright Gary Sinise Mykelti Wil...,"[{'name': 'Alan Silvestri', 'gender': 2, 'depa...",Robert Zemeckis
4,5,American Beauty,Drama,en,15000000,80.878605,15-09-1999,356296601,122,7.9,...,http://www.dreamworks.com/ab/,male nudity female nudity adultery midlife cri...,"Lester Burnham, a depressed suburban father in...","[{""name"": ""DreamWorks SKG"", ""id"": 27}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Look closer.,Kevin Spacey Annette Bening Thora Birch Wes Be...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Movie_ID                  457 non-null    int64
 1   Movie_Title               457 non-null    object
 2   Movie_Genre               457 non-null    object
 3   Movie_Language            457 non-null    object
 4   Movie_Budget              457 non-null    int64
 5   Movie_Popularity          457 non-null    float64
 6   Movie_Release_Date        457 non-null    object
 7   Movie_Revenue             457 non-null    int64
 8   Movie_Runtime             457 non-null    int64
 9   Movie_Vote                457 non-null    float64
 10  Movie_Vote_Count          457 non-null    int64
 11  Movie_Homepage            187 non-null    object
 12  Movie_Keywords            455 non-null    object
 13  Movie_Overview            457 non-null    object
 14  Movie_Production_House    457 non-null    object
 15  Movie_Production_Country  457 non-null    object
 16  Movie_Spoken_Language     457 non-null    object
 17  Movie_Tagline             425 non-null    object
 18  Movie_Cast                456 non-null    object
 19  Movie_Crew                456 non-null    object
 20  Movie_Director            453 non-null    object
dtypes: float64(2), int64(5), object(14)
memory usage: 75.1+ KB

In [ ]:
df.columns

Index(['Movie_ID', 'Movie_Title', 'Movie_Genre', 'Movie_Language',
       'Movie_Budget', 'Movie_Popularity', 'Movie_Release_Date',
       'Movie_Revenue', 'Movie_Runtime', 'Movie_Vote', 'Movie_Vote_Count',
       'Movie_Homepage', 'Movie_Keywords', 'Movie_Overview',
       'Movie_Production_House', 'Movie_Production_Country',
       'Movie_Spoken_Language', 'Movie_Tagline', 'Movie_Cast', 'Movie_Crew',
       'Movie_Director'],
      dtype='object')

In [ ]:
df.describe()

,Movie_ID,Movie_Budget,Movie_Popularity,Movie_Revenue,Movie_Runtime,Movie_Vote,Movie_Vote_Count
count,457.000000,4.570000e+02,457.000000,4.570000e+02,457.000000,457.000000,457.000000
mean,424.120350,3.820555e+07,36.203263,1.548600e+08,119.190372,6.815536,1366.652079
std,355.991716,4.462266e+07,31.656865,2.171718e+08,24.395698,0.873413,1688.385847
min,1.000000,0.000000e+00,0.132878,0.000000e+00,70.000000,3.000000,3.000000
25%,115.000000,6.000000e+06,15.280261,1.693088e+07,102.000000,6.300000,302.000000
50%,229.000000,2.400000e+07,27.788067,7.657864e+07,116.000000,6.900000,750.000000
75%,825.000000,5.300000e+07,45.996110,1.868836e+08,129.000000,7.400000,1746.000000
max,939.000000,3.000000e+08,271.972889,1.845034e+09,229.000000,8.500000,12002.000000

In [ ]:
df.shape

(457, 21)

### **Get Feature Selection**

In [ ]:
df_features = df[['Movie_Genre','Movie_Keywords','Movie_Tagline','Movie_Cast','Movie_Director']].fillna('')

In [ ]:
df_features.shape

(457, 5)

In [ ]:
df_features

,Movie_Genre,Movie_Keywords,Movie_Tagline,Movie_Cast,Movie_Director
0,Crime Comedy,hotel new year's eve witch bet hotel room,Twelve outrageous guests. Four scandalous requ...,Tim Roth Antonio Banderas Jennifer Beals Madon...,Allison Anders
1,Adventure Action Science Fiction,android galaxy hermit death star lightsaber,"A long time ago in a galaxy far, far away...",Mark Hamill Harrison Ford Carrie Fisher Peter ...,George Lucas
2,Animation Family,father son relationship harbor underwater fish...,"There are 3.7 trillion fish in the ocean, they...",Albert Brooks Ellen DeGeneres Alexander Gould ...,Andrew Stanton
3,Comedy Drama Romance,vietnam veteran hippie mentally disabled runni...,"The world will never be the same, once you've ...",Tom Hanks Robin Wright Gary Sinise Mykelti Wil...,Robert Zemeckis
4,Drama,male nudity female nudity adultery midlife cri...,Look closer.,Kevin Spacey Annette Bening Thora Birch Wes Be...,Sam Mendes
...,...,...,...,...,...
452,Drama History War,berlin poison dictator clerk ideology,"April 1945, a nation awaits its...Downfall",Bruno Ganz Alexandra Maria Lara Corinna Harfou...,Oliver Hirschbiegel
453,Drama,christianity jewry roman empire jesus christ s...,"By his wounds, we were healed.",Jim Caviezel Maia Morgenstern Monica Bellucci ...,Mel Gibson
454,Drama Action War History,japan war crimes sense of guilt swordplay general,"In the face of an enemy, in the heart of one m...",Tom Cruise Ken Watanabe William Atherton Chad ...,Edward Zwick
455,Crime Drama Mystery,upper class poison sailboat rape sexual abuse,They're dying to play with you.,Matt Dillon Kevin Bacon Denise Richards Neve C...,John McNaughton
456,Thriller Action Drama Music Romance,sister sister relationship anonymous letter di...,Never let her out of your sigh,,

In [ ]:
x = df_features['Movie_Genre'] + ' ' + df_features['Movie_Keywords'] + ' ' + df_features['Movie_Tagline'] + ' ' + df_features['Movie_Cast']+ ' ' + df_features['Movie_Director']

In [ ]:
x.shape

(457,)

**Get Features Text Conversion to Tokens**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
x = tfidf.fit_transform(x)

In [ ]:
x.shape

(457, 4558)

In [ ]:
print(x)

  (0, 140)	0.15593087726400748
  (0, 116)	0.1664189057445146
  (0, 4074)	0.15593087726400748
  (0, 2563)	0.14848950263307206
  (0, 2511)	0.1664189057445146
  (0, 327)	0.15593087726400748
  (0, 2066)	0.11263069641018703
  (0, 290)	0.1664189057445146
  (0, 177)	0.1664189057445146
  (0, 3455)	0.15593087726400748
  (0, 4050)	0.1081855040792394
  (0, 2381)	0.08315733612647604
  (0, 2944)	0.062296498335723954
  (0, 4442)	0.1664189057445146
  (0, 1437)	0.09390533323698931
  (0, 4428)	0.1081855040792394
  (0, 2091)	0.14271752404693783
  (0, 4010)	0.09863026932863088
  (0, 2965)	0.07931820617514566
  (0, 1004)	0.13056009952162956
  (0, 1404)	0.11608470767005151
  (0, 1854)	0.21371743564810558
  (0, 1961)	0.15195186025109358
  (0, 363)	0.1664189057445146
  (0, 2435)	0.15593087726400748
  :	:
  (455, 4530)	0.11518302848432747
  (455, 1145)	0.0622128191195304
  (455, 3297)	0.17045855355546308
  (455, 4023)	0.1499860901668195
  (455, 921)	0.091816707077094
  (456, 3692)	0.27451184346110724
  (456, 261)	0.27451184346110724
  (456, 2990)	0.27451184346110724
  (456, 451)	0.27451184346110724
  (456, 1102)	0.27451184346110724
  (456, 2364)	0.27451184346110724
  (456, 171)	0.27451184346110724
  (456, 3712)	0.4116817974111638
  (456, 2361)	0.24493687733414946
  (456, 1821)	0.20177423664834018
  (456, 4532)	0.17219927052138242
  (456, 4040)	0.09115674386433487
  (456, 2826)	0.17030261796448398
  (456, 2999)	0.1914844167349054
  (456, 2881)	0.194646430269193
  (456, 3432)	0.11256721272002572
  (456, 1145)	0.06988669758165769
  (456, 3336)	0.15118645279149648
  (456, 33)	0.09911048759480114
  (456, 2944)	0.10275951835403208

**Get Similarity Score Using Cosine Similarity**

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
Similarity_Score = cosine_similarity(x)

In [ ]:
Similarity_Score

array([[1.        , 0.01470627, 0.03883775, ..., 0.07309781, 0.00574116,
        0.00640156],
       [0.01470627, 1.        , 0.00875938, ..., 0.02329392, 0.        ,
        0.0075858 ],
       [0.03883775, 0.00875938, 1.        , ..., 0.03768306, 0.04182172,
        0.01650699],
       ...,
       [0.07309781, 0.02329392, 0.03768306, ..., 1.        , 0.00318044,
        0.04165523],
       [0.00574116, 0.        , 0.04182172, ..., 0.00318044, 1.        ,
        0.00434785],
       [0.00640156, 0.0075858 , 0.01650699, ..., 0.04165523, 0.00434785,
        1.        ]])

In [ ]:
Similarity_Score.shape

(457, 457)

**Get Movie Name as Input form User & Validate for Closest Spelling**

In [ ]:
Favourite_Movie_Name = input(' Enter your favourite movie name :')

In [ ]:
All_Movies_Title_List = df['Movie_Title'].tolist()

In [ ]:
import difflib

In [ ]:
Movie_Recommendation = difflib.get_close_matches(Favourite_Movie_Name, All_Movies_Title_List)
print(Movie_Recommendation)

In [ ]:
Close_Match = Movie_Recommendation[0]
print(Close_Match)

In [ ]:
Index_of_Close_Match_Movie = df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]
print(Index_of_Close_Match_Movie)

In [ ]:
Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)

In [ ]:
len(Recommendation_Score)

### **Get All Movies Sort Based on Recommendation Score wrt Favourite Movie**

In [ ]:
Sorted_Similar_Movies = sorted(Recommendation_Score, key = lambda x:x[1], reverse = True)
print(Sorted_Similar_Movies)

In [ ]:
print('Top 30 Movies Suggested for You : \n')

i = 1
for movie in Sorted_Similar_Movies:
  index = movie[0]
  title_from_index = df[df.index==index]['Movie_Title'].values[0]
  if (i<31):
    print(i, '.',title_from_index)
    i+=1

**Top 10 Movie Recommendation System**

In [ ]:
Movie_Name = input('Enter Your Favourite Movie Name: ')

list_of_all_titles = df['Movie_Title'].tolist()

Find_Close_Match = difflib.get_close_matches(Movie_Name, list_of_all_titles)

Close_Match = Find_Close_Match[0]

Index_of_Movie = df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]

Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Movie]))

sorted_similar_movies = sorted(Recommendation_Score, key = lambda x:x[1], reverse = True)

print('Top 10 Movies Suggested For You : \n')

i = 1
for movie in Sorted_Similar_Movies:
  index = movie[0]
  title_from_index = df[df.Movie_ID==index]['Movie_Title'].values
  if(i<11):
    print(i, '.',title_from_index)
    i+=1